name: 'CFX Portal Upload'
description: 'Upload files to CFX.re Portal automatically'
author: 'HeyyCzer'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  portal-token:
    description: 'CFX Portal authentication token'
    required: true
  asset-id:
    description: 'Asset ID to upload to'
    required: true
  asset-name:
    description: 'Name of the asset'
    required: true
  file-path:
    description: 'Path to the file to upload'
    required: true
  zip-enabled:
    description: 'Enable zip creation (true/false)'
    required: false
    default: 'false'
  zip-files:
    description: 'YAML array of files/folders to include in zip (e.g., "[src/, dist/main.js, README.md]" or multiline YAML list)'
    required: false
  zip-output-path:
    description: 'Output path for the zip file'
    required: false
    default: './dist/output.zip'
  log-level:
    description: 'Logging level (e.g., debug, info, warn, error)'
    required: false
    default: 'info'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install Chrome dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ca-certificates \
          fonts-liberation \
          libappindicator3-1 \
          libasound2t64 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libc6 \
          libcairo2 \
          libcups2 \
          libdbus-1-3 \
          libexpat1 \
          libfontconfig1 \
          libgbm1 \
          libgcc1 \
          libglib2.0-0 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libstdc++6 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxi6 \
          libxrandr2 \
          libxrender1 \
          libxss1 \
          libxtst6 \
          lsb-release \
          wget \
          xdg-utils
      shell: bash
    
    - name: Install dependencies
      run: bun install
      shell: bash
      working-directory: ${{ github.action_path }}
    
    - name: Run CFX Portal Upload
      run: bun run src/index.ts
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        PORTAL_TOKEN: ${{ inputs.portal-token }}
        PORTAL_ASSET_ID: ${{ inputs.asset-id }}
        PORTAL_ASSET_NAME: ${{ inputs.asset-name }}
        FILE_TO_UPLOAD: ${{ inputs.file-path }}
        ZIP_ENABLED: ${{ inputs.zip-enabled }}
        ZIP_FILES: ${{ inputs.zip-files }}
        ZIP_OUTPUT_PATH: ${{ inputs.zip-output-path }}
        LOG_LEVEL: ${{ inputs.log-level }}
        USER_WORKSPACE: ${{ github.workspace }}
        NODE_ENV: 'production'
